import { useEffect, useRef, useCallback, useState } from 'react';
import { useNavigate } from 'react-router';

import { useUIStore } from '@/stores';
import { Logo } from '@/shared/icons/Logo';
import './landing.css';

const CODE_LINES = [
  '<span class="c"># generated by ARCH · main.tf</span>',
  '',
  '<span class="k">resource</span> <span class="s">"aws_vpc"</span> <span class="s">"main"</span> {',
  '  <span class="n">cidr_block</span>           = <span class="s">"10.0.0.0/16"</span>',
  '  <span class="n">enable_dns_hostnames</span> = <span class="n">true</span>',
  '  <span class="n">tags</span> = { <span class="n">Name</span> = <span class="s">"main"</span> }',
  '}',
  '',
  '<span class="k">resource</span> <span class="s">"aws_instance"</span> <span class="s">"web"</span> {',
  '  <span class="n">ami</span>           = <span class="n">var</span>.ami_id',
  '  <span class="n">instance_type</span> = <span class="s">"t3.medium"</span>',
  '  <span class="n">subnet_id</span>     = <span class="n">aws_subnet</span>.public.id',
  '  <span class="n">vpc_security_group_ids</span> = [<span class="n">aws_security_group</span>.web.id]',
  '}',
  '',
  '<span class="k">resource</span> <span class="s">"aws_db_instance"</span> <span class="s">"postgres"</span> {',
  '  <span class="n">identifier</span>        = <span class="s">"app-db"</span>',
  '  <span class="n">engine</span>            = <span class="s">"postgres"</span>',
  '  <span class="n">engine_version</span>    = <span class="s">"16.3"</span>',
  '  <span class="n">instance_class</span>    = <span class="s">"db.t4g.medium"</span>',
  '  <span class="n">allocated_storage</span> = <span class="n">20</span>',
  '  <span class="n">vpc_security_group_ids</span> = [<span class="n">aws_security_group</span>.db.id]',
  '}',
];

const ANIMATION_FRAMES = [
  { delay: 250, node: 0 },
  { delay: 500, node: 1 },
  { delay: 150, wire: 0 },
  { delay: 400, node: 2 },
  { delay: 150, wire: 1 },
];

const STAGE_META: Record<string, string> = {
  designer: 'diagram → main.tf',
  visualizer: 'repo → topology',
};

export const LandingPage = () => {
  const theme = useUIStore((s) => s.theme);
  const setTheme = useUIStore((s) => s.setTheme);
  const navigate = useNavigate();

  const [activeTab, setActiveTab] = useState<'designer' | 'visualizer'>('designer');

  const canvasRef = useRef<HTMLDivElement>(null);
  const wiresSvgRef = useRef<SVGSVGElement>(null);
  const nodeRefs = useRef<(HTMLDivElement | null)[]>([]);
  const wireRefs = useRef<(SVGPathElement | null)[]>([]);
  const codeRef = useRef<HTMLPreElement>(null);

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    document.documentElement.classList.toggle('dark', theme === 'dark');
  }, [theme]);

  const layoutWires = useCallback(() => {
    const canvas = canvasRef.current;
    const svg = wiresSvgRef.current;
    if (!canvas || !svg) return;

    const cb = canvas.getBoundingClientRect();
    svg.setAttribute('viewBox', `0 0 ${cb.width} ${cb.height}`);

    const anchor = (el: HTMLDivElement | null) => {
      if (!el) return { x: 0, top: 0, bot: 0 };
      const r = el.getBoundingClientRect();
      return {
        x: r.left - cb.left + r.width / 2,
        top: r.top - cb.top,
        bot: r.top - cb.top + r.height,
      };
    };

    const a = anchor(nodeRefs.current[0]);
    const b = anchor(nodeRefs.current[1]);
    const c = anchor(nodeRefs.current[2]);

    const sy = a.bot;
    wireRefs.current[0]?.setAttribute(
      'd',
      `M ${a.x} ${sy} C ${a.x} ${(sy + b.top) / 2}, ${b.x} ${(sy + b.top) / 2}, ${b.x} ${b.top}`,
    );
    wireRefs.current[1]?.setAttribute(
      'd',
      `M ${a.x} ${sy} C ${a.x} ${(sy + c.top) / 2}, ${c.x} ${(sy + c.top) / 2}, ${c.x} ${c.top}`,
    );
  }, []);

  useEffect(() => {
    layoutWires();
    const raf1 = requestAnimationFrame(() => requestAnimationFrame(layoutWires));
    const timeout = setTimeout(layoutWires, 400);
    window.addEventListener('resize', layoutWires);
    return () => {
      cancelAnimationFrame(raf1);
      clearTimeout(timeout);
      window.removeEventListener('resize', layoutWires);
    };
  }, [layoutWires]);

  useEffect(() => {
    const cancelled = { current: false };

    const wait = (ms: number) =>
      new Promise<void>((resolve) => {
        const id = setTimeout(() => resolve(), ms);
        const check = setInterval(() => {
          if (cancelled.current) {
            clearTimeout(id);
            clearInterval(check);
            resolve();
          }
        }, 100);
      });

    const run = async () => {
      while (!cancelled.current) {
        const nodes = nodeRefs.current;
        const wires = wireRefs.current;
        const code = codeRef.current;

        nodes.forEach((n) => n?.classList.remove('on', 'highlight'));
        wires.forEach((w) => w?.classList.remove('on'));
        if (code) code.innerHTML = '';

        for (const frame of ANIMATION_FRAMES) {
          if (cancelled.current) return;
          await wait(frame.delay);
          if (cancelled.current) return;

          if (frame.node !== undefined) {
            const n = nodes[frame.node];
            n?.classList.add('on', 'highlight');
            setTimeout(() => n?.classList.remove('highlight'), 450);
          }
          if (frame.wire !== undefined) {
            wires[frame.wire]?.classList.add('on');
          }
        }

        await wait(300);

        for (let i = 0; i < CODE_LINES.length; i++) {
          if (cancelled.current) return;
          if (!code) break;

          const prev = code.querySelector('.cursor');
          if (prev) prev.remove();

          const div = document.createElement('div');
          div.innerHTML = CODE_LINES[i] + '<span class="cursor"></span>';
          code.appendChild(div);

          await wait(CODE_LINES[i].trim().length === 0 ? 40 : 90);
        }

        await wait(2800);

        const cur = code?.querySelector('.cursor');
        if (cur) cur.remove();

        await wait(400);
      }
    };

    run();
    return () => {
      cancelled.current = true;
    };
  }, []);

  return (
    <div className="landing">
      {/* TOP BAR */}
      <div className="topbar">
        <div className="wrap row">
          <div className="brand">
            <span className="glyph">
              <Logo size={20} className="text-ink" />
            </span>
            <span className="name"><b>INFRA</b>WEAVER</span>
          </div>
          <nav className="nav">
            <button className="theme-toggle" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle theme">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
                <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z" />
              </svg>
            </button>
          </nav>
        </div>
      </div>

      {/* HERO */}
      <section className="hero">
        <div className="wrap">
          <span className="eyebrow">
            <span className="dot" />
            VISUAL INFRASTRUCTURE PLATFORM
          </span>

          <h1 className="hero-title">
            Stop <span className="strike">writing</span> Terraform.
            <br />
            <em>Draw it.</em>
          </h1>

          <p className="hero-sub">
            Design, generate, and sync cloud systems visually.
            <br />
            From architecture to production-ready code — and back.
          </p>

          <div className="cta-row">
            <button className="btn btn-primary" onClick={() => navigate('/app')}>
              Launch InfraWeaver
              <svg className="arr" width="13" height="13" viewBox="0 0 16 16" fill="none">
                <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
            <button className="btn btn-ghost" onClick={() => window.open('https://github.com/fabiog96/InfraWeaver', '_blank')}>
              <svg width="13" height="13" viewBox="0 0 16 16" fill="currentColor">
                <path d="M8 0C3.58 0 0 3.58 0 8a8 8 0 0 0 5.47 7.59c.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.42 7.42 0 0 1 4 0c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8" />
              </svg>
              Visualize a repo
            </button>
          </div>

          {/* STAGE */}
          <div className="stage" aria-hidden="true">
            <div className="stage-head">
              <div className="tabs">
                <button
                  className={`tab ${activeTab === 'designer' ? 'active' : ''}`}
                  onClick={() => setActiveTab('designer')}
                >
                  <span className="dot" />DESIGNER
                </button>
                <button
                  className={`tab ${activeTab === 'visualizer' ? 'active' : ''}`}
                  onClick={() => setActiveTab('visualizer')}
                >
                  <span className="dot" />VISUALIZER
                </button>
              </div>
              <span className="meta">{STAGE_META[activeTab]}</span>
            </div>

            {/* Designer pane */}
            <div className={`stage-body ${activeTab === 'designer' ? 'active' : ''}`}>
              <div className="canvas" ref={canvasRef}>
                <svg ref={wiresSvgRef} preserveAspectRatio="none">
                  <path ref={(el) => { wireRefs.current[0] = el; }} className="wire" d="" />
                  <path ref={(el) => { wireRefs.current[1] = el; }} className="wire" d="" />
                </svg>
                <div ref={(el) => { nodeRefs.current[0] = el; }} className="node" style={{ left: '34%', top: '14%' }}>
                  <div className="hdr"><span className="sq" />NETWORK</div>
                  <div className="nm">vpc · main</div>
                </div>
                <div ref={(el) => { nodeRefs.current[1] = el; }} className="node" style={{ left: '8%', top: '58%' }}>
                  <div className="hdr"><span className="sq" />COMPUTE</div>
                  <div className="nm">ec2 · web</div>
                </div>
                <div ref={(el) => { nodeRefs.current[2] = el; }} className="node" style={{ left: '58%', top: '62%' }}>
                  <div className="hdr"><span className="sq" />DATABASE</div>
                  <div className="nm">rds · postgres</div>
                </div>
              </div>
              <div className="code">
                <pre ref={codeRef} />
              </div>
            </div>

            {/* Visualizer pane */}
            <div className={`stage-body ${activeTab === 'visualizer' ? 'active' : ''}`}>
              <div className="viz-code">
                <pre
                  dangerouslySetInnerHTML={{
                    __html: `<span class="c"># modules/network/main.tf</span>
<span class="k">resource</span> <span class="s">"aws_vpc"</span> <span class="s">"main"</span> {
  <span class="n">cidr_block</span> = <span class="s">"10.0.0.0/16"</span>
<span class="hl">  <span class="n">tags</span> = {
    <span class="n">Project</span> = <span class="s">"platform"</span>
    <span class="n">Layer</span>   = <span class="s">"network"</span>
  }</span>
}

<span class="c"># modules/compute/main.tf</span>
<span class="k">resource</span> <span class="s">"aws_instance"</span> <span class="s">"api"</span> {
  <span class="n">instance_type</span> = <span class="s">"t3.medium"</span>
<span class="hl">  <span class="n">tags</span> = {
    <span class="n">Project</span> = <span class="s">"platform"</span>
    <span class="n">Layer</span>   = <span class="s">"compute"</span>
  }</span>
}`,
                  }}
                />
              </div>
              <div className="viz-graph">
                <div className="cluster net">
                  <div className="c-head">
                    <span className="tag"><b /> LAYER / NETWORK</span>
                    <span className="cnt">1</span>
                  </div>
                  <div className="pile">
                    <span className="vnode"><span className="d" />vpc · main</span>
                  </div>
                </div>
                <div className="cluster">
                  <div className="c-head">
                    <span className="tag"><b /> LAYER / COMPUTE</span>
                    <span className="cnt">1</span>
                  </div>
                  <div className="pile">
                    <span className="vnode"><span className="d" />ec2 · api</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* HOW */}
      <section className="how">
        <div className="wrap">
          <div className="grid">
            <div>
              <div className="kicker">— HOW</div>
              <h2>
                Four steps.
              </h2>
              <h2><em>No DSL.</em></h2>
            </div>
            <div className="steps">
              <div className="step">
                <span className="num">01</span>
                <span className="ttl">Draw the topology</span>
                <span className="tag">CANVAS</span>
              </div>
              <div className="step">
                <span className="num">02</span>
                <span className="ttl">
                  Generate <em>Terraform + Terragrunt</em>
                </span>
                <span className="tag">HCL</span>
              </div>
              <div className="step">
                <span className="num">03</span>
                <span className="ttl">Review a normal PR</span>
                <span className="tag">GIT</span>
              </div>
              <div className="step">
                <span className="num">04</span>
                <span className="ttl">
                  Apply — or visualize what's <em>already there</em>
                </span>
                <span className="tag">TWO-WAY</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* AWS-FIRST */}
      <section className="aws">
        <div className="wrap">
          <div className="aws-box">
            <div>
              <div className="kicker">— STACK</div>
              <p className="lead">
                Today, <em>AWS-first.</em>
                <br />
                Tomorrow, wherever your team ships.
              </p>
            </div>
            <div className="aws-stack">
              <div className="item">
                <span className="nm">AWS</span>
                <span className="pill">LIVE</span>
              </div>
              <div className="item">
                <span className="nm">Terraform</span>
                <span className="pill">LIVE</span>
              </div>
              <div className="item">
                <span className="nm">Terragrunt</span>
                <span className="pill">LIVE</span>
              </div>
              <div className="item soon">
                <span className="nm">GCP · Azure · K8s</span>
                <span className="pill">SOON</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FINAL CTA */}
      <section className="final">
        <div className="wrap">
          <h2>
            Your next architecture is
            <br />
            <em>production-ready</em>.
          </h2>
          <div className="cta-row">
            <button className="btn btn-primary" onClick={() => navigate('/app')}>
              Launch InfraWeaver
              <svg className="arr" width="13" height="13" viewBox="0 0 16 16" fill="none">
                <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer>
        <div className="wrap" style={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
          <span>&copy; 2026 InfraWeaver</span>
          <span>draw &rarr; generate &rarr; deploy</span>
        </div>
      </footer>
    </div>
  );
};
