import type { Node } from '@xyflow/react';

import type { TechNodeData } from '@/shared/types';
import type { GlobalConfig } from './root-renderer';
import { getModule } from '../data/module-registry';
import type { FolderNode } from './folder-structure-generator';

const renderTree = (node: FolderNode, prefix: string = '', isLast: boolean = true): string => {
  const connector = prefix === '' ? '' : isLast ? '`-- ' : '|-- ';
  const lines: string[] = [`${prefix}${connector}${node.name}`];

  if (node.children) {
    const childPrefix = prefix === '' ? '' : prefix + (isLast ? '    ' : '|   ');
    node.children.forEach((child, i) => {
      lines.push(renderTree(child, childPrefix, i === node.children!.length - 1));
    });
  }

  return lines.join('\n');
};

export const renderReadme = (
  config: GlobalConfig,
  nodes: Node[],
  folderTree: FolderNode,
): string => {
  const secrets = new Set<string>();
  const modules: { label: string; moduleId: string; description: string }[] = [];

  for (const node of nodes) {
    if (node.type !== 'tech') continue;
    const data = node.data as TechNodeData;
    if (!data.moduleId) continue;

    const tfModule = getModule(data.moduleId);
    if (!tfModule) continue;

    modules.push({
      label: data.label,
      moduleId: data.moduleId,
      description: tfModule.category,
    });

    for (const secret of tfModule.secrets) {
      const name = data.terraformSecrets?.[secret.name] || secret.name.toUpperCase();
      secrets.add(name);
    }
  }

  const lines: string[] = [];

  lines.push(`# ${config.project} - Infrastructure`);
  lines.push('');
  lines.push(`Terragrunt-managed infrastructure for **${config.project}** (${config.subproject}).`);
  lines.push('');
  lines.push('## Prerequisites');
  lines.push('');
  lines.push('- [Terraform](https://www.terraform.io/downloads) >= 1.9.0');
  lines.push('- [Terragrunt](https://terragrunt.gruntwork.io/docs/getting-started/install/) >= 0.67.0');
  lines.push('- [AWS CLI](https://aws.amazon.com/cli/) configured with appropriate credentials');
  lines.push('');
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  lines.push('cd infrastructure-live');
  lines.push('terragrunt run-all init');
  lines.push('terragrunt run-all plan');
  lines.push('terragrunt run-all apply');
  lines.push('```');
  lines.push('');
  lines.push('## Configuration');
  lines.push('');
  lines.push(`| Parameter | Value |`);
  lines.push(`|-----------|-------|`);
  lines.push(`| Region | \`${config.region}\` |`);
  lines.push(`| Environment | \`${config.environment}\` |`);
  lines.push(`| State Bucket | \`${config.stateBucket}\` |`);
  lines.push(`| Lock Table | \`${config.lockTable}\` |`);
  lines.push('');

  if (modules.length > 0) {
    lines.push('## Modules');
    lines.push('');
    lines.push('| Module | Category |');
    lines.push('|--------|----------|');
    for (const mod of modules) {
      lines.push(`| ${mod.label} | ${mod.description} |`);
    }
    lines.push('');
  }

  lines.push('## Folder Structure');
  lines.push('');
  lines.push('```');
  lines.push(renderTree(folderTree));
  lines.push('```');
  lines.push('');

  if (secrets.size > 0) {
    lines.push('## Environment Variables');
    lines.push('');
    lines.push('The following environment variables must be set:');
    lines.push('');
    for (const secret of secrets) {
      lines.push(`- \`${secret}\``);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Diagrammer Farm*');
  lines.push('');

  return lines.join('\n');
};
