import { type ComponentType, memo } from 'react';

import {
  AwsApiGateway,
  AwsAppSync,
  AwsAthena,
  AwsAurora,
  AwsBackup,
  AwsBatch,
  AwsBedrock,
  AwsCertificateManager,
  AwsCloudFormation,
  AwsCloudFront,
  AwsCloudTrail,
  AwsCloudWatch,
  AwsCloudWatchAlarm,
  AwsCloudWatchEventEventBased,
  AwsCodeBuild,
  AwsCodeDeploy,
  AwsCodePipeline,
  AwsCognito,
  AwsDirectConnect,
  AwsDocumentDb,
  AwsDynamoDb,
  AwsDynamoDbStream,
  AwsEc2,
  AwsEfs,
  AwsElastiCache,
  AwsElasticBeanstalk,
  AwsElasticBlockStore,
  AwsElasticContainerRegistry,
  AwsElasticContainerService,
  AwsElasticKubernetesService,
  AwsElasticLoadBalancing,
  AwsEmr,
  AwsEventBridge,
  AwsEventBridgeRule,
  AwsEventBridgeScheduler,
  AwsFargate,
  AwsGlobalAccelerator,
  AwsGlue,
  AwsGuardDuty,
  AwsIdentityAndAccessManagement,
  AwsKeyManagementService,
  AwsKinesis,
  AwsLambda,
  AwsLightsail,
  AwsMq,
  AwsNeptune,
  AwsPrivateLink,
  AwsQuickSuite,
  AwsRds,
  AwsRedshift,
  AwsRoute53,
  AwsSageMaker,
  AwsSecretsManager,
  AwsSimpleNotificationService,
  AwsSimpleNotificationServiceTopic,
  AwsSimpleQueueService,
  AwsSimpleQueueServiceQueue,
  AwsSimpleStorageService,
  AwsSimpleStorageServiceGlacier,
  AwsSimpleStorageServiceS3Standard,
  AwsStepFunctions,
  AwsSystemsManager,
  AwsTransitGateway,
  AwsVirtualPrivateCloud,
  AwsVpcNatGateway,
  AwsWaf,
  AwsXRay,
} from '@cloud-icons/react/aws';

type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

const iconMap: Record<string, IconComponent> = {
  'aws-ec2': AwsEc2,
  'aws-lambda': AwsLambda,
  'aws-fargate': AwsFargate,
  'aws-batch': AwsBatch,
  'aws-lightsail': AwsLightsail,
  'aws-elastic-beanstalk': AwsElasticBeanstalk,
  'aws-ecs': AwsElasticContainerService,
  'aws-eks': AwsElasticKubernetesService,
  'aws-ecr': AwsElasticContainerRegistry,
  'aws-s3': AwsSimpleStorageService,
  'aws-efs': AwsEfs,
  'aws-ebs': AwsElasticBlockStore,
  'aws-glacier': AwsSimpleStorageServiceGlacier,
  'aws-backup': AwsBackup,
  'aws-rds': AwsRds,
  'aws-dynamodb': AwsDynamoDb,
  'aws-dynamodb-streams': AwsDynamoDbStream,
  'aws-elasticache': AwsElastiCache,
  'aws-aurora': AwsAurora,
  'aws-redshift': AwsRedshift,
  'aws-neptune': AwsNeptune,
  'aws-documentdb': AwsDocumentDb,
  'aws-cloudfront': AwsCloudFront,
  'aws-api-gateway': AwsApiGateway,
  'aws-elb': AwsElasticLoadBalancing,
  'aws-route53': AwsRoute53,
  'aws-vpc': AwsVirtualPrivateCloud,
  'aws-nat-gateway': AwsVpcNatGateway,
  'aws-transit-gateway': AwsTransitGateway,
  'aws-direct-connect': AwsDirectConnect,
  'aws-privatelink': AwsPrivateLink,
  'aws-global-accelerator': AwsGlobalAccelerator,
  'aws-s3-event': AwsSimpleStorageServiceS3Standard,
  'aws-cloudwatch-alarm': AwsCloudWatchAlarm,
  'aws-cloudwatch-event': AwsCloudWatchEventEventBased,
  'aws-cognito-trigger': AwsCognito,
  'aws-eventbridge-rule': AwsEventBridgeRule,
  'aws-eventbridge-scheduler': AwsEventBridgeScheduler,
  'aws-sns-topic': AwsSimpleNotificationServiceTopic,
  'aws-sqs-queue': AwsSimpleQueueServiceQueue,
  'aws-sns': AwsSimpleNotificationService,
  'aws-sqs': AwsSimpleQueueService,
  'aws-mq': AwsMq,
  'aws-eventbridge': AwsEventBridge,
  'aws-step-functions': AwsStepFunctions,
  'aws-appsync': AwsAppSync,
  'aws-iam': AwsIdentityAndAccessManagement,
  'aws-cognito': AwsCognito,
  'aws-waf': AwsWaf,
  'aws-guardduty': AwsGuardDuty,
  'aws-secrets-manager': AwsSecretsManager,
  'aws-kms': AwsKeyManagementService,
  'aws-acm': AwsCertificateManager,
  'aws-cloudwatch': AwsCloudWatch,
  'aws-xray': AwsXRay,
  'aws-cloudtrail': AwsCloudTrail,
  'aws-kinesis': AwsKinesis,
  'aws-athena': AwsAthena,
  'aws-glue': AwsGlue,
  'aws-emr': AwsEmr,
  'aws-quicksight': AwsQuickSuite,
  'aws-sagemaker': AwsSageMaker,
  'aws-bedrock': AwsBedrock,
  'aws-codepipeline': AwsCodePipeline,
  'aws-codebuild': AwsCodeBuild,
  'aws-codedeploy': AwsCodeDeploy,
  'aws-cloudformation': AwsCloudFormation,
  'aws-systems-manager': AwsSystemsManager,
};

interface AwsIconProps {
  icon: string;
  className?: string;
}

const RawAwsIcon = ({ icon, className }: AwsIconProps) => {
  const Icon = iconMap[icon];
  if (!Icon) return null;

  return <Icon size="100%" className={className} />;
};

export const AwsIcon = memo(RawAwsIcon);
